*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 09.02.2022 at 02:39:08
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZSFE_V_ORDER_PRO................................*
FORM GET_DATA_ZSFE_V_ORDER_PRO.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZSFE_D_ORDER_PRO WHERE
(VIM_WHERETAB) .
    CLEAR ZSFE_V_ORDER_PRO .
ZSFE_V_ORDER_PRO-MANDT =
ZSFE_D_ORDER_PRO-MANDT .
ZSFE_V_ORDER_PRO-ORDER_ID =
ZSFE_D_ORDER_PRO-ORDER_ID .
ZSFE_V_ORDER_PRO-PRODUCT_ID =
ZSFE_D_ORDER_PRO-PRODUCT_ID .
ZSFE_V_ORDER_PRO-ORDER_PRO_ID =
ZSFE_D_ORDER_PRO-ORDER_PRO_ID .
    SELECT SINGLE * FROM ZSFE_D_ORDER WHERE
ORDER_ID = ZSFE_D_ORDER_PRO-ORDER_ID .
    IF SY-SUBRC EQ 0.
    ENDIF.
    SELECT SINGLE * FROM ZSFE_D_PRODUCT WHERE
PRODUCT_ID = ZSFE_D_ORDER_PRO-PRODUCT_ID .
    IF SY-SUBRC EQ 0.
    ENDIF.
<VIM_TOTAL_STRUC> = ZSFE_V_ORDER_PRO.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZSFE_V_ORDER_PRO .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZSFE_V_ORDER_PRO.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZSFE_V_ORDER_PRO-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZSFE_D_ORDER_PRO WHERE
  ORDER_ID = ZSFE_V_ORDER_PRO-ORDER_ID AND
  PRODUCT_ID = ZSFE_V_ORDER_PRO-PRODUCT_ID AND
  ORDER_PRO_ID = ZSFE_V_ORDER_PRO-ORDER_PRO_ID .
    IF SY-SUBRC = 0.
    DELETE ZSFE_D_ORDER_PRO .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZSFE_D_ORDER_PRO WHERE
  ORDER_ID = ZSFE_V_ORDER_PRO-ORDER_ID AND
  PRODUCT_ID = ZSFE_V_ORDER_PRO-PRODUCT_ID AND
  ORDER_PRO_ID = ZSFE_V_ORDER_PRO-ORDER_PRO_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZSFE_D_ORDER_PRO.
    ENDIF.
ZSFE_D_ORDER_PRO-MANDT =
ZSFE_V_ORDER_PRO-MANDT .
ZSFE_D_ORDER_PRO-ORDER_ID =
ZSFE_V_ORDER_PRO-ORDER_ID .
ZSFE_D_ORDER_PRO-PRODUCT_ID =
ZSFE_V_ORDER_PRO-PRODUCT_ID .
ZSFE_D_ORDER_PRO-ORDER_PRO_ID =
ZSFE_V_ORDER_PRO-ORDER_PRO_ID .
    IF SY-SUBRC = 0.
    UPDATE ZSFE_D_ORDER_PRO .
    ELSE.
    INSERT ZSFE_D_ORDER_PRO .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZSFE_V_ORDER_PRO-UPD_FLAG,
STATUS_ZSFE_V_ORDER_PRO-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZSFE_V_ORDER_PRO.
  SELECT SINGLE * FROM ZSFE_D_ORDER_PRO WHERE
ORDER_ID = ZSFE_V_ORDER_PRO-ORDER_ID AND
PRODUCT_ID = ZSFE_V_ORDER_PRO-PRODUCT_ID AND
ORDER_PRO_ID = ZSFE_V_ORDER_PRO-ORDER_PRO_ID .
ZSFE_V_ORDER_PRO-MANDT =
ZSFE_D_ORDER_PRO-MANDT .
ZSFE_V_ORDER_PRO-ORDER_ID =
ZSFE_D_ORDER_PRO-ORDER_ID .
ZSFE_V_ORDER_PRO-PRODUCT_ID =
ZSFE_D_ORDER_PRO-PRODUCT_ID .
ZSFE_V_ORDER_PRO-ORDER_PRO_ID =
ZSFE_D_ORDER_PRO-ORDER_PRO_ID .
    SELECT SINGLE * FROM ZSFE_D_ORDER WHERE
ORDER_ID = ZSFE_D_ORDER_PRO-ORDER_ID .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
    SELECT SINGLE * FROM ZSFE_D_PRODUCT WHERE
PRODUCT_ID = ZSFE_D_ORDER_PRO-PRODUCT_ID .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZSFE_V_ORDER_PRO USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZSFE_V_ORDER_PRO-ORDER_ID TO
ZSFE_D_ORDER_PRO-ORDER_ID .
MOVE ZSFE_V_ORDER_PRO-PRODUCT_ID TO
ZSFE_D_ORDER_PRO-PRODUCT_ID .
MOVE ZSFE_V_ORDER_PRO-ORDER_PRO_ID TO
ZSFE_D_ORDER_PRO-ORDER_PRO_ID .
MOVE ZSFE_V_ORDER_PRO-MANDT TO
ZSFE_D_ORDER_PRO-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZSFE_D_ORDER_PRO'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZSFE_D_ORDER_PRO TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZSFE_D_ORDER_PRO'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZSFE_V_ORDER_PRO USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZSFE_D_ORDER_PRO-MANDT =
ZSFE_V_ORDER_PRO-MANDT .
ZSFE_D_ORDER_PRO-ORDER_ID =
ZSFE_V_ORDER_PRO-ORDER_ID .
ZSFE_D_ORDER_PRO-PRODUCT_ID =
ZSFE_V_ORDER_PRO-PRODUCT_ID .
ZSFE_D_ORDER_PRO-ORDER_PRO_ID =
ZSFE_V_ORDER_PRO-ORDER_PRO_ID .
    SELECT SINGLE * FROM ZSFE_D_ORDER WHERE
ORDER_ID = ZSFE_D_ORDER_PRO-ORDER_ID .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
    SELECT SINGLE * FROM ZSFE_D_PRODUCT WHERE
PRODUCT_ID = ZSFE_D_ORDER_PRO-PRODUCT_ID .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
